local set = function(bg)
  vim.api.nvim_set_hl(0, "Normal", { bg = bg })
  vim.api.nvim_set_hl(0, "NormalFloat", { bg = bg })
  vim.api.nvim_set_hl(0, "FloatBorder", { bg = bg })
  vim.api.nvim_set_hl(0, "Pmenu", { bg = bg })
  vim.api.nvim_set_hl(0, "Terminal", { bg = bg })
  vim.api.nvim_set_hl(0, "EndOfBuffer", { bg = bg })
  vim.api.nvim_set_hl(0, "FoldColumn", { bg = bg })
  vim.api.nvim_set_hl(0, "Folded", { bg = bg })
  vim.api.nvim_set_hl(0, "SignColumn", { bg = bg })
  vim.api.nvim_set_hl(0, "NormalNC", { bg = bg })
  vim.api.nvim_set_hl(0, "WhichKeyFloat", { bg = bg })
  vim.api.nvim_set_hl(0, "TelescopeBorder", { bg = bg })
  vim.api.nvim_set_hl(0, "TelescopeNormal", { bg = bg })
  vim.api.nvim_set_hl(0, "TelescopePromptBorder", { bg = bg })
  vim.api.nvim_set_hl(0, "TelescopePromptTitle", { bg = bg })

  vim.api.nvim_set_hl(0, "NeoTreeNormal", { bg = bg })
  vim.api.nvim_set_hl(0, "NeoTreeNormalNC", { bg = bg })
  vim.api.nvim_set_hl(0, "NeoTreeVertSplit", { bg = bg })
  vim.api.nvim_set_hl(0, "NeoTreeWinSeparator", { bg = bg })
  vim.api.nvim_set_hl(0, "NeoTreeEndOfBuffer", { bg = bg })

  vim.api.nvim_set_hl(0, "NvimTreeNormal", { bg = bg })
  vim.api.nvim_set_hl(0, "NvimTreeVertSplit", { bg = bg })
  vim.api.nvim_set_hl(0, "NvimTreeEndOfBuffer", { bg = bg })

  vim.api.nvim_set_hl(0, "NotifyINFOBody", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyERRORBody", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyWARNBody", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyTRACEBody", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyDEBUGBody", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyINFOTitle", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyERRORTitle", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyWARNTitle", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyTRACETitle", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyDEBUGTitle", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyINFOBorder", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyERRORBorder", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyWARNBorder", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyTRACEBorder", { bg = bg })
  vim.api.nvim_set_hl(0, "NotifyDEBUGBorder", { bg = bg })

  vim.api.nvim_set_hl(0, "LineNr", { bg = bg })
  vim.api.nvim_set_hl(0, "CursorLineNr", { bg = bg })

  vim.api.nvim_set_hl(0, "StatusLine", { bg = bg })
  vim.api.nvim_set_hl(0, "StatusLineNC", { bg = bg })

  vim.api.nvim_set_hl(0, "TabLine", { bg = bg, fg = "#6c6c6c" })
  vim.api.nvim_set_hl(0, "TabLineSel", { bg = bg, fg = "#ffffff" })
  vim.api.nvim_set_hl(0, "TabLineFill", { bg = bg })
end

return set
