return {
  { "tjdevries/colorbuddy.nvim" },
  { "tjdevries/gruvbuddy.nvim" },
  { "folke/tokyonight.nvim" },
  { "rose-pine/neovim" },
  { "Mofiqul/dracula.nvim" },
  { "navarasu/onedark.nvim" },
  { "ribru17/bamboo.nvim" },
  { "catppuccin/nvim" },
  { "savq/melange-nvim" },
  { "ramojus/mellifluous.nvim" },
  { "blazkowolf/gruber-darker.nvim" },
  { "aliqyan-21/darkvoid.nvim" },
  { "ficcdaf/ashen.nvim" },
}
